
spring:
  cloud:
    alicloud:
      access-key: LTAI5t9Qia5jwRTebHpvaxNm
      secret-key: YfZsyjykY3pNymRlXtvW388Deo47hy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: ebook-trading-platform


server:
  port: 8088
